### ISSUE TITLE
Procédure d'installation

### ISSUE THREAD

**Issue by jfpace** [AriiPortal/Arii#8]
Bonjour,

Peut-on mettre au point une procédure d'installation  d'ARII V2 ?

L'environnement cible de cette installation est une distribution Centos Version 7.3 minimale (ou RHEL).

Tous les composants pré-requis suivants sont supposés installés et fonctionnels.

    Système d’exploitation : Linux CentOS V7.3
    Serveur HTTP Apache V2.4.x
    Serveur de pages PHP 5.6.x
    Oracle® Database Java® Runtime Environment (JRE) 64-Bit version 1.8.x
    Interpréteur de script Perl V5.2x.x
    Le logiciel graphique Graphviz V2.38
    Le logiciel de gestion de versions Git V1.7
    Le framework « Symphony » V2.x
    Le logiciel Arii V1.x
    Serveur GIT
    JobScheduler V1.9.x
     une base de données (préférentiellement MariaDB)

La façon dont ils sont installés est décrite içi 
`http://wiki.sos-paris.com/index.php/Installer_Arii_composant_par_composant_sur_une_Centos_7.3`

Il faut revoir comment on récupère les sources (notamment quelle version) et quelles sont les opérations à suivre pour installer et démarrer Arii.

Une fois cette installation au point, nous prendrons en charge la mise au point des autres moyens d'installer : container et VM.
Nous tenons une vm avec les pré-requis à disposition si besoin 

merci

jf

**Comment by AriiPortal** [comment]
Bonjour,

C'est une très bonne procédure d'installation pour la partie LAMP, jusqu'à l'installation de Symfony.
Pour la partie Ari'i, cette procédure me semble plus juste: http://wiki.sos-paris.com/index.php/Draft_Installation

La procédure utilise une version 2.7.5, or il faut une version 2.8 pour la configuration LDAP: http://symfony.com/blog/new-in-symfony-2-8-ldap-component
Le bundle FOSUserBundle doit être installé.

Si l'installation de Symfony2 est fonctionnelle, on peut y héberger une nouvelle application Arii, il y a beaucoup de guide sur le sujet, par exemple celui-ci: http://iabsis.com/fr/community/tuto/first-symfony2-app

Une procédure basique serait la suivante:
- aller src
- créer un répertoire Arii
- aller dans Arii
- cloner les modules:
`git clone https://github.com/AriiPortal/UserBundle`
`git clone https://github.com/AriiPortal/CoreBundle`
- ajouter le routage dans app/config/routing.yml
```
arii_homepage:
    path:  /
    defaults: {_controller: AriiCoreBundle:Default:default }

arii_home:
    path:  /home/{_locale}
    defaults: { _controller: AriiCoreBundle:Default:index }
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp

# ========================================
# Core Bundle
# ----------------------------------------
arii_core:
    resource: "@AriiCoreBundle/Resources/config/routing.yml"
    prefix:   /home/{_locale}
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp

# ========================================
# User Bundle
# ----------------------------------------
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password

arii_user:
    resource: "@AriiUserBundle/Resources/config/routing.yml"
    prefix:   /user/{_locale}
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp
```
- préciser la langue française dans le fichier parameters.yml:
```
parameters:
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: fr
```
- Ajouter l'application dans  app/appKernel.php:
```
    public function registerBundles()
    {
        $bundles = array(
        new Symfony\Bundle\FrameworkBundle\FrameworkBundle(),
        new Symfony\Bundle\SecurityBundle\SecurityBundle(),
        new Symfony\Bundle\TwigBundle\TwigBundle(),
        new Symfony\Bundle\MonologBundle\MonologBundle(),
        new Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle(),
        new Doctrine\Bundle\DoctrineBundle\DoctrineBundle(),
        new Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle(),
        new FOS\UserBundle\FOSUserBundle(),
        new Arii\UserBundle\AriiUserBundle(),
        new Arii\CoreBundle\AriiCoreBundle(),
```
- Mettre à jour la base de données
`php app/console doctrine:schema:update --force`
- Configurer la partie sécurité suivant vos besoin dans app/config/security.yml
Pour l'exemple, le mien ressmble à ceci:
```
security:
#    always_authenticate_before_granting: true    
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_SYSADMIN,ROLE_OPERATOR,ROLE_DEVELOPPER]
        ROLE_MANAGER:     [ROLE_USER,ROLE_OPERATOR,ROLE_DEVELOPPER]
        ROLE_OPERATOR:    [ROLE_USER]
        ROLE_DEVELOPPER:  [ROLE_USER]       
        ROLE_SYSADMIN:    [ROLE_ALLOWED_TO_SWITCH,ROLE_DEVELOPPER]

    providers:
        chain_provider:
            chain:
                providers: [fos_userbundle, app_users, in_memory]
        in_memory:
            memory:
                users:
                    sos:  { password: sospass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        fos_userbundle:
            id: fos_user.user_provider.username

        app_users:
            ldap:
                service: app.ldap
                base_dn: dc=vaudoise,dc=ch
                search_dn: [VOTRE CN]
                search_password: [PASSWORD UD COMPTE]
                filter: (sAMAccountName={username})
                default_roles: ROLE_USER
                
    firewalls:
        ldap:
            provider:  app_users
            stateless: true
            pattern:   /joc/
            http_basic_ldap:
                service: app.ldap
                dn_string: "{username}@vaudoise.ch"
                
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js|pdf)/
            security: false

        cron:
            pattern:  /cron/
            security: false

        mft:
            pattern:  /mft/
            security: false

        doc:
            pattern:  /doc/
            security: false

        post:
            pattern:  /post/
            security: false
            
        public:
            pattern:  /(public)
            security: false

        report:
            pattern:  /(report)/
            security: false
            
        check:
            pattern:  /(check)/
            anonymous: false
            http_basic:
                realm: "Secured Area"
                provider: fos_userbundle
            
        user:
            pattern:  ^/(user)/
            security: false

        # Firewall pour le cache
        cache:
            pattern:    ^/cache
            anonymous: false
            http_basic:
                realm: "Secured Area"
                provider: fos_userbundle

        requests:
            pattern:  /(requests)/
            security: false

        login:
            pattern:   ^/(login$|register|resetting|sync_state)  # Les adresses de ces pages sont login, register 
            security: false
        
        main:
            pattern:    ^/  # Tout est protégé
            provider: app_users
            pattern:  ^/admin
            form_login_ldap:
                service: app.ldap
                dn_string: [VOTRE CHAINE]
                check_path: fos_user_security_check
                login_path: fos_user_security_login
                remember_me: true            # On active la possibilité du "Se souvenir de moi" (désactivé par défaut)
            form_login:
                provider:    fos_userbundle  # On lit l'authentification au provider définit plus haut
                remember_me: true            # On active la possibilité du "Se souvenir de moi" (désactivé par défaut)
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: arii_Home_index
            logout:
                path:   fos_user_security_logout
                target: fos_user_security_login
                # invalidate_session: true
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"
            remember_me:
                key:      %secret%        # On définit la clé pour le remember_me (%secret% est un parametre de parameters.ini)
                lifetime: 31536000 # 365 days in seconds
#                path:     /login
#                domain:   ~ # Defaults to the current domain from $_SERVER

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
```
- La configuration globale est dans app/config/config.yml
```
Mon fichier pour une utilisation avec CentOS/Oracle est le suivant:
imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: true
                dql:
                    datetime_functions:
                        Month: Arii\CoreBundle\DQL\Month
                        Year: Arii\CoreBundle\DQL\Year

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Configuration FOSUserBundle
fos_user:
    db_driver:     orm                        # Le type de BDD à utiliser, nous utilisons l'ORM Doctrine depuis le début
    firewall_name: main                       # Le nom du firewall duquel on utilisera ces utilisateurs
    user_class:    Arii\UserBundle\Entity\User # La classe de l'entité User que nous venons de définir

services:
    # Oracle
    my.listener:
        class: Doctrine\DBAL\Event\Listeners\OracleSessionInit
        tags:
            - { name: doctrine.event_listener, event: postConnect }
```

Mes conseils avant de se lancer directement sur une installation CentOS/Oracle:
- il faut comprendre les principes de Symfony2
- faire une installation de symfony sur une plateforme simple (Ex: windows/mysql ou linux/mysql)
- ajouter l'installation de arii sur cette plateforme après avoir vérifié que tout était fonctionnel
- installer les modules les uns après les autres pour identifier le module qui pourrait poser problème
- ne pas oublier les différentes étapes (clone, route, config, mise à jour de la base de données, etc...)

Bonne journée, 
Eric

**Comment by jfpace** [comment]
Nous avons suivi la procédure.
Premier pb : perte des images. Contrournement en installant assetic et en récupérant un folder ariicore avec les images, icones...
Nous avons installe les bundle user et core. 
Puis admin et  DS bundle. Mais il ya un appel à FocusBundle (est-ce une dépendance de DS ?) et ce bundle n'existe pas/plus.
Du coup, je me demande si on est installe les bonnes versions des bundles.
Apparement le master à 2 ans. 

voici le message  👍 
```
[arii@Centos03_AriiV2 Arii]$ git clone https://github.com/AriiPortal/AdminBundle
Cloning into 'AdminBundle'...
remote: Counting objects: 972, done.
remote: Compressing objects: 100% (113/113), done.
remote: Total 972 (delta 72), reused 0 (delta 0), pack-reused 859
Receiving objects: 100% (972/972), 316.86 KiB | 0 bytes/s, done.
Resolving deltas: 100% (627/627), done.
[arii@Centos03_AriiV2 Arii]$ git clone https://github.com/AriiPortal/DSBundle
Cloning into 'DSBundle'...
remote: Counting objects: 161, done.
remote: Total 161 (delta 0), reused 0 (delta 0), pack-reused 161
Receiving objects: 100% (161/161), 45.76 KiB | 0 bytes/s, done.
Resolving deltas: 100% (76/76), done.
[arii@Centos03_AriiV2 Arii]$ git clone https://github.com/AriiPortal/FocusBundle
Cloning into 'FocusBundle'...
Username for 'https://github.com': jfpace
Password for 'https://jfpace@github.com':
remote: Repository not found.
fatal: repository 'https://github.com/AriiPortal/FocusBundle/' not found
[arii@Centos03_AriiV2 Arii]$ git clone https://github.com/AriiPortal/FocusBundle
Cloning into 'FocusBundle'...
Username for 'https://github.com': jfpace
Password for 'https://jfpace@github.com':
remote: Repository not found.
fatal: repository 'https://github.com/AriiPortal/FocusBundle/' not found
[arii@Centos03_AriiV2 Arii]$
```
Nous avons travaillé aussi sur le jid et rencontré une erreur (cf image jointe).
Je ne comprends pas sa signification.
![image2](https://cloud.githubusercontent.com/assets/17028741/25359209/9357920e-2944-11e7-9968-9e772e52d5ce.png)

Pourrions-nous lister les modules 'de base' ? Un ordre d'install est-il à suivre ?
peux-tu flaguer la version (corebundle j'imagine)  à utiliser et créer les submodules versions correspondants ?.

**Comment by AriiPortal** [comment]
Bonjour,

Il y a 3 phases:
- Installation de Symfony (FosUserBundle)
- Installation du Portail (CoreBundle) 
- Installation des modules (JID, Graphviz)

Le message est une suite de git clone donc j'en déduis que vous êtes déjà en phase 3. Il aurait été préférable de vérifier la phase 2 avant de se lancer dans une suite de module.
Le premier problème est une question d'assets, il s'agit de faire un lien entre le répertoire des images qui est dans le répertoire des modules et le répertoire web public.
Le plus efficace est la commande suivante: http://symfony.com/blog/new-in-symfony-2-6-smarter-assets-install-command

Pour le message du JID, je vous renvoie sur la procédure d'ajout de module: http://wiki.sos-paris.com/index.php/Ajouter_un_nouveau_module
et plus précisément sur la partie kernel et routage
http://wiki.sos-paris.com/index.php/Ajouter_un_nouveau_module#Kernel_et_routage
"as such a route does not exists" signifie que vous n'avez pas respecté cette étape.

Flagger les versions et créer des sous-modules est ce qu'il faut faire dans une équipe de développeur, cela sera certainement mis en place lorsque l'équipe s'agrandira.

Bonne journée,
Eric

**Comment by jfpace** [comment]
Bonjour,

Les phases 1 et 2 ont été faites jusqu'à disparation des erreurs d'installation.
Nous les avons testées en ouvrant le portail. A la connexion, message d'erreur : il lui manque des bundles (normal, ils ne sont pas installés).
Comment tester autrement qu'en naviguant sur le portail ? 

Je vais tester "smarter asset install", et revoir le routage du JID comme tu le conseilles.

Il est entendu que tu géres une seule version. La question est juste de distinguer ce qui est en dev et ce qu'on peut installer. La réponse que je comprends pour le moment est  'toujours installer la dernière version sauf indication particulière'. est-ce correct ?  



Bonne journée.
jf

**Comment by AriiPortal** [comment]
Tout à fait correct.

A noter que dés que le portail est installé, les erreurs sont journalisées, un export de ces données permettra ensuite d'accélérer le diagnostic.

**Comment by jfpace** [comment]
Bonjour,

Ok pour systèmatiser la remontée des logs de Symfony.

Pour l'install : nous avons passé la commande 
`php app/console assets:install` 
qui a créé le repretoire et copier des fichiers.
Visiblement plus efficace que assetics, je vais modifier la proc dans ce sens.

Nous avons installé tous les bundles suivnats : core, user, admin, jid, ds, graphviz, joc, report.

MFT nous a donné une erreur d'accès à la BDD.
J'ai regardé la doc du module, rien trouvé de particulier. 
MFT n'est pas strtégique pour le moment et l'erreur est visiblement un oubli.
Nous avons desinstallé MFT pour pouvoir continuer.
Ce module est-il obligatoire au bon foncitonnement du portail ?

Tous les autres bundles ont été installé sans erreur symfony.

Lorsqu'on va sur le portail, on a la page de login. Nous avions créé un user, on se logue et la page reste blanche. Entièrement blanche, aucune erreur 400 ou 500.
En mode dev on a récupéré les logs apache et symfony, ils sont en pj.

En étudiant le parameters.yml on a retrouvé des données venant d'une mac windows. 'C:/Xamp...'
Je ne sais pas d'ou elles viennent.


Le fichier routing.yml est plus petit qu'avant : disparition de paragraphes de jid-public de jid nagios, du housekeeping...;
Est-ce normal ?

Peux-tu nos faire une archive Symfony+portail fonctionnelle ? ca nous permettrait d'avoir un poinht de comparaison pourl'install par composant et commencer des tests.

Bonne journée.

JF
[LOGS ERREUR INSTALL ARII V2.docx](https://github.com/AriiPortal/Arii/files/957514/LOGS.ERREUR.INSTALL.ARII.V2.docx)

**Comment by AriiPortal** [comment]
La bonne commande est 
`php app/console assets:install --symlink`

comme indiqué dans la section suivante:
http://wiki.sos-paris.com/index.php/Installer_Arii_composant_par_composant_sur_une_Centos_7.3#Installation_des_assets

Elle permet, quand c'est possible, de faire nu lien et pas une copie de fichiers. Si on travaille en lien, la mise à jour d'un module modifie aussi la partie web alors qu'en travaillant en copie il faudra penser à relancer la même commande pour mettre à jour les fichiers.

MFT ne sert qu'au transfert de fichiers, il n'est pas nécessaire.

Il semble que vous continuez à mélanger une ancienne version avec une mise à jour, le fichier parameters doit être celui créé à l'installation de symfony. Voici le mien:
```
# This file is auto-generated during the composer install
parameters:
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: fr
    secret: e7e1603f5100ce280eb3a33584cd625a4ce9d26b

    database_driver: mysqli
    database_host: 127.0.0.1
    database_port: 3306
    database_name: arii
    database_user: root
    database_password: null
```

Pouvez vous me confirmer que vous êtres parti d'une nouvelle installation et pas d'une installation existante ? Ce fichier ne devrait rien contenir.

Pour le routing, le but est d'avoir strictement la même configuration quel que soit le module, ceci afin de pouvoir automatiser l'activation et la désactivation d'un module. C'est ce qui est indiqué dans le lien envoyé hier: http://wiki.sos-paris.com/index.php/Ajouter_un_nouveau_module#Kernel_et_routage

Une page blanche signifie généralement que vous êtes en train de regarder le cache et non pas ce qui est installé. 
Pour les tests, il est préférable d'utiliser l'url de dev:
`http://localhost/app_dev.php/login`

Pour tout mise à jour, il faut vider le cache, la commande est dans la procédure d'installation:
`php app/console cache:clear`
on peut aussi directement supprimer les fichiers dans app/cache

Je viens de l'ajouter dans la procédure de mise à jour d'un module.

Les logs ne servent à rien si le cache n'est pas effacé car cela reviendrait à diagnostiquer le cache et non pas ce qui est installé.

Faire une archive dans l'état actuel est une mauvaise idée, je préfère que vous continuez à comprendre le framework, d'autant que sans ces connaissances vous ne pourrez pas identifier les bons fichiers.

Bonne journée,
Eric

**Comment by jfpace** [comment]
Bonjour,

Ok pour  le lien symbolique, ca me parait plus efficace.
Je vais modifier la préocédure dans ce s

Nous ne travailllons pas sur une ancienne version. Nous vidons le cache et testons en mode dev (il me semble que dans ce mode, la vm n'utilise pas le chache, tu confirmes ?)
Lorsque nous sommes bloqués dans une procédure, nuos comparons avec ce que nos connaissons cqd l'ancienne version d'où surement ton impresssion que nous utilisons une vielle version.
En fait, quand nous recommencons nosu effacons le  repertoire symfony pour être surs de ne pas avoir de reliquat de l'ancienne installation.
Nous fiasons aussi des restart du apapche pour recharger les configs.

J'avais un doute sur les droits (le repertoire web n'est pas dans l'emplacment habituel) mais nous sommes attentifs à ce point et s'il y avait des pr d'accès on aurait un message d'erreur.
Ceci dit, je ne sais pas pourquoi rien ne s'affiche, sans détection d'aucune erreur importante.
On doit faire un bétise qq part , une grosse  puisqu'on ne la voit pas.

Je pense que nous sommes assez proches du but, c'est pour cela que je te demandais une archive et pour paralléliser les tests (claude) et l'install (séfié et moi).

Comme on a maintenant beaucoup d'infos, je vais rejouer la procédure depuis symfony et valider les fichiers parameters, routing, config.
 Je te remonterai toutes les erreurs afin d'avoir une procédure complète et opérationnelle.
jf

**Comment by AriiPortal** [comment]
Bonjour, 

Le cache est un mécanisme de symfony, il est généralement utilisé en mode production (http://localhost/app.php) mais désactivé en mode dev (http://localhost/app_dev.php). Son utilisation ne dépend donc ni d'arii ni de la plateforme sur laquelle il est installé.
L'impression de réutilisation vient de l'indication "En étudiant le parameters.yml on a retrouvé des données venant d'une mac windows. 'C:/Xamp...'", c'est assez curieux car le paremeters.yml ne se remplit pas tout seul. Eventuellement, le seul module qui écrit dans le fichier est le JOE.

Bonne journée, 
Eric

**Comment by jfpace** [comment]
Je ne comprends pas d'ou viennent des infos : cela vient d'une  machine windows alors que nous travaillons seulement sous linux.

**Comment by AriiPortal** [comment]
Je peux voir la partie du parameters.yml qui contient ces informations ?

**Comment by jfpace** [comment]
Non, désolé j'ai tout jeté et recommancé. 
Peux-tu me donner  copie du  AppBundle.php dans ...../src/AppBundle, stp ?
JE me demande si nous n'avons pas un soucis sur le FOSUserBundle
Merci.

**Comment by AriiPortal** [comment]
Bonjour,

Je n'ai pas de AppBundle. 

Eric

**Comment by jfpace** [comment]
Bonjour,
Cela pose un pb car tous les tutoriels d'install de FOSUserBundle le mentionnent
comment installes-tu ce bundle alors ?

**Comment by AriiPortal** [comment]
Je pense qu'on parle d'une illustration, comme monsieur X pour une personne.
Est il possible d'avoir un lien sur l'une de ces procédures pour confirmer ?

**Comment by jfpace** [comment]
oui,
la procédure officielle 
http://symfony.com/doc/current/bundles/FOSUserBundle/index.html
step 3

**Comment by jfpace** [comment]
Bonjour,
Nous avons refait la procédure sur une autre vm.
La rédaction de l'install a évolué.
Nous avons toujours un pb d'affichage blanc (en dev) et aucune erreur nulle part.

Je joins le fichier log de Symfony. Nous l'aovns vidé puis rehcargé la page.
As-tu une idée ? 
[logs symfony.txt](https://github.com/AriiPortal/Arii/files/981060/logs.symfony.txt)

Il faudra revoir cette procédure pour une isntallation dans les folders habituels (du style /var/www) car nous sommes obligés d'ouvrir des droits sur les folders du home.

bon we

jf

**Comment by jfpace** [comment]
et ca ?
http://symfony.com/doc/2.8/setup/file_permissions.html

**Comment by jfpace** [comment]
Je viens de voir que la procédure ne comportait pas d'installation de DHTMLX.
J'ai cherché dans le wiki et trouvé ca : [http://wiki.sos-paris.com/index.php/Installation_OJS_debian#Instalation_silencieuse_d.27OpenSource_JobScheduler]
avec ces infos 👍 

```
## pre-requis
cd $HOME/web/
git clone https://github.com/DHTMLX/scheduler.git
mv scheduler dhtmlx_scheduler 
git clone https://github.com/DHTMLX/gantt.git 
mv gantt dhtmlx_gantt 
cd $HOME/vendor/ 
git clone https://github.com/DHTMLX/connector-php.git 
mv connector-php dhtmlx 
git clone https://github.com/erusev/parsedown.git 
```
Est-ce à jour et complet ?
sinon quels sont les modules nécéssaires et ou les placer ?

jf

**Comment by AriiPortal** [comment]
Bonjour,

Cette issue part dans tous les sens, cela explique en partie les problèmes d'installation.
1) concernant le appBundle:
"The doc uses a bundle named AppBundle according to the Symfony best practices. However, you can of course place your user class in the bundle you want."
Donc, appBundle est un exemple, dans le cas d'Arii le module User est simple UserBundle qui est une extension du FosUserBundle.

2) comme indiqué précédemment et à plusieurs reprises, il me parait plus constructif de démarrer par une installation standard plutôt que par des spécificités. La première étape est d'installer symphony puis d'ajouter les modules, est ce que vous avez réussi à installer symfony et accéder à la page d'accueil à un moment ?

3) je mets la doc à jour pour les extensions web et vendor.

Bonne journée.

**Comment by AriiPortal** [comment]
J'ai besoin du contenu du répertoire app/config

**Comment by jfpace** [comment]
Bonjour,

J'ai la page d'accueil. 

Il y a qq précautions à prendre en installant dhtmlx.
Le readme sur arii n'était plus à jour. 
J'ai soumis le readme avec corrections. 

J'en suis au point suivant : tous les modules apparaissent mais ne s'affichent pas quand on clique, c'est la page d'acceuil se recharge. Je pense que c'est un réglage dans le routing .yml tous les modules pointent vers  /home/{_locale} et qu'ils reviennent à l'index s'ils ne trouvent rien.

Mais tu avais fait cette  V2  pour  stocker ces infos en bdd pour simplifier l'administration.
Quelle opération faut-il faire ?.
La bdd est opérationnelle, (via phpmyadmin, on y accède).

JF

**Comment by jfpace** [comment]
Fichier config en pj
[config.zip](https://github.com/AriiPortal/Arii/files/984187/config.zip)
Bonne journée.
jf

**Comment by AriiPortal** [comment]
Il faut ajouter:
`    locale: fr
`
dans le bloc parameters du fichier app/parameters.yml
Exemple:
```
parameters:
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: fr
    secret: e7e1603f5100ce280eb3a33584cd625a4ce9d26b
```
